upgrade and use vendored h5p
openstax/h5p-runner pull request #3
Opened 2024-04-04 20:50 UTC by jivey

https://openstax.atlassian.net/browse/DISCO-80
https://openstax.atlassian.net/browse/DISCO-81

This copies the latest js and css from the main h5p library into vendor, which resolves the two above accessibility issues (and likely more.)

I copied how the h5p-standalone configures webpack to get things working when requiring, but I'm unsure if there's a simpler way. Also, I'm unsure if you'd prefer to have everything in `loadVendor` by wrapping the requires in Promises... it seemed unnecessary but maybe it's preferable to keep it consolidated there.

2024-04-08 18:11 UTC, TomWoodward requested changes
my initial inclination was to put everything in the loadVendor function, i'm assuming you ran into some issue with that. maybe dependency management between the h5p vendor files? 

in any case, maybe its better to do the  bundling anyway, but maybe we should include the css files also and remove the whole `loadVendor` thing? also i don't think you necessarily need to use `require` right? you could use regular imports at the top of the file?

2024-04-11 21:22 UTC, jivey commented
@TomWoodward Yeah I couldn't get them to import properly, though I forget what the error message was. I took another look today and I think I was overcomplicating things. I liked your idea of importing it all directly for our bundle, so I've updated to do that, and everything seems to still work?

2024-04-12 01:25 UTC, TomWoodward requested changes
Why do they all need ts ignores? Can you set allow js in the tsconfig ?

2024-04-19 17:59 UTC, TomWoodward approved these changes

2024-04-19 18:03 UTC, merged